/*
 * Question Generator
 * Provides a method that generates simple math questions, provides the answer
 * and four options.
 *
 * Varun Gonsalves, Kaif Kutchwala, Emmanuel Leo
 *
 * Date: 07/05/2023
 *
 */

#include <string.h>

/*
 * Define a function pointer type named "Operation"
 * that takes two floats as arguments and returns a float.
 */
typedef float (*Operation)(float, float);

/*
 * This struct represents a multiple choice question generated by
 * QuestionGenerator_generateQuestion.
 */
typedef struct {
    char text[30];   // Text of the question
    int answer;      // Value of the correct answer
    int options[4];  // Array of options
} QuestionResult;

/*
 * QuestionGenerator_generateQuestion
 * This function is generates a simple math question involving a
 * random operation between 2 random numbers based on the specified difficulty.
 * The operation will be either add, subtract, multiple or divide.
 * The numbers are generated within the range 1-100
 *
 * If difficulty is high, the 2 numbers will be larger.
 * The question text is in the form "What is {number1}{operation_symbol}{number2}?"
 * The answer is an integer.
 * The options is an array of integers including the answer.
 *
 * Input:
 * 		difficulty:	   This will be between 1-3, which will set the difficulty of the question
 *
 * Output:
 *		QuestionResult: A struct containing the following properties
 * 			text:		This will be the text of the question
 * 			answer:		This is the answer to the question as in integer
 * 			options:	4 options are provided including the answer
 */
QuestionResult QuestionGenerator_generateQuestion(unsigned int difficulty);
